services:
  ros:
    build: .
    container_name: create3_container
    volumes:
      - ./gtl_pkg:/root/create3_ws/src/gtl_pkg
    environment:
      # Enter your ip, followed by :0.0, below
      - DISPLAY=10.2.0.3:0.0
    tty: true
    stdin_open: true
